In [1]:
import numpy as np
import random
"Create array"
arr = np.array([1,2,3,4,5,6,7,8,10])
print(arr)
"2d array"
#%timeit 
arr1 = np.array([[random.randrange(1,7)for _ in range(20)],[random.randrange(1,7)for _ in range(20)]])
print(arr1)
arr1

[ 1  2  3  4  5  6  7  8 10]
[[3 5 4 2 5 4 4 2 2 6 1 4 6 6 3 5 2 1 1 3]
 [1 6 3 5 6 6 2 2 1 4 3 2 3 4 2 1 5 5 3 4]]


array([[3, 5, 4, 2, 5, 4, 4, 2, 2, 6, 1, 4, 6, 6, 3, 5, 2, 1, 1, 3],
       [1, 6, 3, 5, 6, 6, 2, 2, 1, 4, 3, 2, 3, 4, 2, 1, 5, 5, 3, 4]])

ndArray Attribute

In [4]:
#Type of element in ndarray
print(arr1.dtype)

#Dimension 1d, 2d etc
print(arr1.ndim)

#Get bytes stored for each element\
print(arr1.itemsize)

#Get the total size of array
print(arr1.size)


#Get number of rows and columns in tuple format
print(arr1.shape)

#Iteration through the array
for rows in arr1:
    for cols in rows:
        print(cols, end= ' ')
    print()
    
#2d array as 1d array
for row in arr1.flat:
    print(row, end= ' ')
    
#Filling up numpy aray with specific values:
print('\n', np.zeros((2,5)))
print(np.ones(shape = (2,4), dtype= int))
print(np.full((3,5),14))

#Create range of int

print(np.arange(5))
print(np.arange(5,10))
print(np.arange(10,2,-3))

#Create range of float 

print(np.linspace(0.0,0.1,num= 5))

#Reshaping Array
print(np.arange(1,21).reshape(4,5))

#Create random integers using numpy
my_arr = np.random.randint(1,7,20).reshape(4,5)
print(my_arr)


int32
2
4
40
(2, 20)
3 5 4 2 5 4 4 2 2 6 1 4 6 6 3 5 2 1 1 3 
1 6 3 5 6 6 2 2 1 4 3 2 3 4 2 1 5 5 3 4 
3 5 4 2 5 4 4 2 2 6 1 4 6 6 3 5 2 1 1 3 1 6 3 5 6 6 2 2 1 4 3 2 3 4 2 1 5 5 3 4 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]]
[[14 14 14 14 14]
 [14 14 14 14 14]
 [14 14 14 14 14]]
[0 1 2 3 4]
[5 6 7 8 9]
[10  7  4]
[0.    0.025 0.05  0.075 0.1  ]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[2 5 6 3 6]
 [5 2 5 6 5]
 [3 2 3 4 1]
 [1 6 5 2 2]]


Numpy array operations between different array using operators

In [20]:
#-- Broadcasting operation where an operation with scalar is considered as operation with array containing all scalar elements
a=arr*2
b=arr+10
c=a*b
print(a,b,c)
print(a<b)
print(a is b)
print(a == b)

[ 2  4  6  8 10 12 14 16 20] [11 12 13 14 15 16 17 18 20] [ 22  48  78 112 150 192 238 288 400]
[ True  True  True  True  True  True  True  True False]
False
[False False False False False False False False  True]


numpy multi dim array operations between elements of same numpy arrray using functions

In [1]:
import numpy as np
grade = np.array([[1,2,3],[0,1,0],[0,2,0],[0,4,0]])
print(grade)
print(grade.sum())
print(grade.max())
print(grade.mean())
print(grade.std())
print(grade.var())
print(grade.mean(axis=0)) #mean by col
print(grade.mean(axis=1)) #mean by row
print(grade.sum(axis=0))  #sum by col
print(grade.sum(axis=1))  #sum by row

[[1 2 3]
 [0 1 0]
 [0 2 0]
 [0 4 0]]
13
4
1.0833333333333333
1.3202482931462383
1.7430555555555556
[0.25 2.25 0.75]
[2.         0.33333333 0.66666667 1.33333333]
[1 9 3]
[6 1 2 4]


Universal Function

In [5]:
no = np.array([random.randrange(1,7)for _ in range(5)])
print(no)
no1= np.sqrt(no)
print(no1)
no3 = np.add(no,no1)
print(no3)

[6 3 6 6 5]
[2.44948974 1.73205081 2.44948974 2.44948974 2.23606798]
[8.44948974 4.73205081 8.44948974 8.44948974 7.23606798]


Index and slice

In [11]:
grade1 = np.array([[0,1,0],[0,2,0],[0,3,0],[0,4,0]])
print(grade1)
print(grade1[0,1])
print(grade1[1,1])
print(grade1[2,1])
print(grade1[3,1])
print(grade1[1])
print(grade1[2])
print(grade1[3])
#print(grade1[4])
print("Select row consecutive")
print(grade1[0:2])
print("select individual row")
print(grade1[[1,3]])
print("select columns")
print(grade1[:,1])
print("select columns consecutive")
print(grade1[:,1:3])
print("select individual columns")
print(grade1[:,[0,2]])

[[0 1 0]
 [0 2 0]
 [0 3 0]
 [0 4 0]]
1
2
3
4
[0 2 0]
[0 3 0]
[0 4 0]
Select row consecutive
[[0 1 0]
 [0 2 0]]
select individual row
[[0 2 0]
 [0 4 0]]
select columns
[1 2 3 4]
select columns consecutive
[[1 0]
 [2 0]
 [3 0]
 [4 0]]
select individual columns
[[0 0]
 [0 0]
 [0 0]
 [0 0]]


Shallow Copy

In [18]:
#Does not modify original array
import numpy as np
u = np.arange(1,10)
v = u.view()
print("Before")
print(u)
print(v)
print("After")
u*=10
print(u)
print(v)
print('slicing')
v = u[:3]  ##Slicing gives a view to original array
print(v)
u +=9
print(v)
print(u)
v*2
print(u)


Before
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
After
[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]
slicing
[10 20 30]
[19 29 39]
[19 29 39 49 59 69 79 89 99]
[19 29 39 49 59 69 79 89 99]


Deep Copy

In [5]:
w = np.arange(1,7)
p = w.copy()
print("Before")
print(w)
print(p)
w+=10
print("After")
print(w)
print(p)

Before
[1 2 3 4 5 6]
[1 2 3 4 5 6]
After
[11 12 13 14 15 16]
[1 2 3 4 5 6]


Reshaping and Transposing Numpy Arrays

In [7]:
#Reshape-- Just a view and does not modify original array shape(shallow copy type)
grade2 = np.array([[0,1,0],[0,2,0],[0,3,0],[0,4,0]])
print(grade2)
grade3 = grade2.reshape(1,12)
print(grade3)
print(grade2)

#Resize-- Can modify original array shape(deep copy type)
grade4 = grade2.resize(1,12)
print('My', grade4)
print(grade2)

#Flatten- Performs deep copy and flatten original array
print('FLATTEN')
grades = np.array([[0,1,0],[0,2,0]])
flat = grades.flatten()
print(flat)
print(grades)

#Ravel - Perform shallow copy
print('RAVEL')
grades6 = np.array([[0,1,0],[0,2,0]])
ravel = grades6.ravel()
print(ravel)
ravel+=10
print(grades6)
grades6*=10
print(ravel)
print(grades6)

#Transposing multi dim Array--Produces vie/shallow copy
print('TRANSPOSE')
grades = np.array([[0,1,0],[0,2,0]])
print(grades)
print("Transposed\n", grades.T)

#H-Stack function for combining 2 arrays
grades2 = np.array([[0,4,0],[0,5,0]])
print('hstack')
print(grades2)
print(np.hstack((grades,grades2)))

#V-Stack
print(grades2.T)
print('vstack')
print(np.vstack((grades.T,grades2.T)))

[[0 1 0]
 [0 2 0]
 [0 3 0]
 [0 4 0]]
[[0 1 0 0 2 0 0 3 0 0 4 0]]
[[0 1 0]
 [0 2 0]
 [0 3 0]
 [0 4 0]]
My None
[[0 1 0 0 2 0 0 3 0 0 4 0]]
FLATTEN
[0 1 0 0 2 0]
[[0 1 0]
 [0 2 0]]
RAVEL
[0 1 0 0 2 0]
[[10 11 10]
 [10 12 10]]
[100 110 100 100 120 100]
[[100 110 100]
 [100 120 100]]
TRANSPOSE
[[0 1 0]
 [0 2 0]]
Transposed
 [[0 0]
 [1 2]
 [0 0]]
hstack
[[0 4 0]
 [0 5 0]]
[[0 1 0 0 4 0]
 [0 2 0 0 5 0]]
[[0 0]
 [4 5]
 [0 0]]
vstack
[[0 0]
 [1 2]
 [0 0]
 [0 0]
 [4 5]
 [0 0]]
